### ISSUE TITLE
Productize Task/ValueTask/Async.`ignore`

### ISSUE THREAD

**Issue by bartelink** [fsprojects/FSharp.Control.TaskSeq#128]
I've long felt icky about using `Async.Ignore`. Seeing the `Async.ignore` that's presently hiding in plain sight here makes me realise the absence of a `Task.ignore` and `ValueTask.ignore` from FSharp.Core is something I've also been grinning and bearing (sprinkling `:> Task` and all sorts of other such mindless hacks). `Utils.fs` presently has helpers that feel very tempting to use more broadly. However, binding  to a set of support helpers on the fringe of this library's core feature set is obviously debatable.

(The other pair from here that I feel deserves a canonical implementation in a library that doesn't include a jungle of other less-related helpers is `Async.ofTask`/`Task.toAsync`, but with corrected `AggregateException` semantics, and honoring of `Async.Cancellation` when compared to `Async.AwaitTask` as per `FSharp.Core`. Will likely calve off a separate issue from this if placeholder `FSharp.Core.TaskShims` package/repo is deemed to be the best home for a set of `ignore` helpers)

related:
- [precursor discussion in PR comments](https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/125#issuecomment-1346666092)
- [add `AwaitTaskCorrect` to FSharp.Core suggestion](https://github.com/fsharp/fslang-suggestions/issues/840)

**Comment by abelbraaksma** [comment]
/cc @dsyme, we should discuss this. Some of this effort may ultimately land back into F# Core, but agreeing on a `TaskEx` library (name tbd) and adding it to the `FsProjects` realm may be a good idea.

This is related to #78

**Comment by TheAngryByrd** [comment]
Yeah I have a lot of the same functions floating around in IcedTasks ([example1](https://github.com/TheAngryByrd/IcedTasks/blob/master/src/IcedTasks/ValueTasks.fs#L20), [example2](https://github.com/TheAngryByrd/IcedTasks/blob/a64e4a3b93145e1b356f0834b5f52c625b54a4da/src/IcedTasks/ValueTasks.fs#L716)) and FsToolkit ([example1](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/2db01da6a1b29222e4fd61ecacef35b6c460d51f/src/FsToolkit.ErrorHandling.TaskResult/Task.fs#L10), [example2](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/2db01da6a1b29222e4fd61ecacef35b6c460d51f/src/FsToolkit.ErrorHandling/Async.fs#L4))

I even have a [tool](https://github.com/demystifyfp/FsToolkit.ErrorHandling/tree/2db01da6a1b29222e4fd61ecacef35b6c460d51f/tools/FunctionMap) that writes out all the functions (like map, bind, apply, zip, etc) and which libraries contain them because it's hard to know who implementing what these days and where the gaps are in functionality.

**Comment by bartelink** [comment]
Closing in favor of #139 (general high level discussion about shimming and/or libraries/projects) and #140 (`ignore` helpers only)

**Comment by bartelink** [comment]
Switching close reason; work is not completed; sorry!

**Comment by abelbraaksma** [comment]
Thanks for writing out these covering issues! Much appreciated!
